Docs for smoke test
drasi-project/docs pull request #50
Opened 2024-10-16 19:24 UTC by ruokun-niu

- Added a page for smoke test under `reference`
  - Updated prereq
  - Updated commands to execute the smoke test
  - Updated smoke test overview
- Added a small section on the installation pages that direct the users to the smoke test page (which is optional)

2024-10-18 15:52 UTC, agentofreality requested changes

2024-10-18 15:52 UTC, agentofreality commented on docs/content/reference/smoke-test/_index.md
This feels like How-To content and should be in the How-To Guides section.

Please put it in a new folder: How-To Guides/Test Drasi

2024-10-18 15:52 UTC, agentofreality commented on docs/content/reference/smoke-test/_index.md
> +title: "Smoke Test"
Smoke Test a Drasi Installation

2024-10-18 15:52 UTC, agentofreality commented on docs/content/reference/smoke-test/_index.md
> +    Smoke test for Drasi Installation
Learn how to quickly test a Drasi installation.

2024-10-18 15:52 UTC, agentofreality commented on docs/content/reference/smoke-test/_index.md
> +
Need a section in here that describes what they will see when the run the test and it is successful, and what they might see of the test fails.

2024-10-22 20:36 UTC, agentofreality requested changes

2024-10-22 20:36 UTC, agentofreality commented on docs/content/how-to-guides/smoke-test/_index.md
> +linkTitle: "Test Drasi"
```suggestion
linkTitle: "Smoke Test a Drasi Installation"
```

2024-10-22 23:18 UTC, agentofreality approved these changes

2024-10-23 12:34 UTC, agentofreality commented
@ruokun-niu lets not merge this. I have taken the changes into the doc work i am doing and will publish it with them.

2024-10-23 16:44 UTC, ruokun-niu commented
Closing this PR

2024-10-23 16:44 UTC, closed without merging