Drasi explorer reference doc update
drasi-project/docs pull request #65
Opened 2024-12-04 01:12 UTC by NValsan

Added description of new Debug, Attach, and Apply capabilities

2024-12-04 20:16 UTC, danielgerlag commented on docs/content/reference/developer-tools/vscode-extension/DrasiExplorerApply.png
I think we should retake these screen shots with the Activity bar on the left, where most people would see it.

2024-12-04 20:16 UTC, danielgerlag commented on docs/content/reference/developer-tools/vscode-extension/DrasiExplorerDebug.png
We should also show these actions in the Code Lens buttons that appear above the YAML in the editor.

2024-12-05 12:35 UTC, agentofreality commented
I dont think this is a Reference section article, I am thinking it should be in the How To section.

2024-12-05 12:37 UTC, agentofreality requested changes

2024-12-05 12:37 UTC, agentofreality commented on docs/content/reference/developer-tools/vscode-extension/_index.md
I dont think this is a Reference section article, I am thinking it should be in the How To section.

It also doesn't describe the full functionality of the extension, there are 3 sections. What is the purpose / functionality of each one and how do I use it?

2024-12-19 18:53 UTC, closed without merging

2024-12-19 18:53 UTC, NValsan commented
Closing to move doc to tutorial section and make requested changes